/**
 * Netflix Cadmium Playercore - Module 63616
 * Extracted from cadmium-playercore-6.0055.939.911.js
 * Purpose: Dependencies: [94469]
 * Original signature: function(t, b, a)
 */

// Webpack module 63616
// Parameters: t (module), b (exports), a (require)
t = a(94469);
export const mK = (0,
t.IH)(("LATENCY_EWMA THROUGHPUT_EWMA THROUGHPUT_SLIDING_WINDOW NETWORK_CONFIDENCE NETWORK_INTERRUPTION THROUGHPUT_PERCENTILE THROUGHPUT_CUMULATIVE NETWORK_ENTROPY DELIVERY_TIME_EWMA THROUGHPUT_T_DIGEST RESPONSE_TIME_BUCKET_PERCENTILES THROUGHPUT_SWITCHES LOW_THROUGHPUT THROUGHPUT_TREND THROUGHPUT_BUCKET_PERCENTILES THROUGHPUT_COEFFICIENT_OF_VARIATION RESPONSE_TIME_AVERAGE").split(" "));
