/**
 * @module PlayerConstants
 * @description Core constants used throughout the Cadmium player, including
 * codec MIME types, DRM system IDs, MP4 box identifiers, time conversion
 * factors, buffer size limits, base64-encoded init segment headers for
 * various video codecs (AVC, HEVC, Dolby Vision), and pre-built encrypted
 * stream headers used for MSE initialization.
 * @origin Module_33096
 */

// ─── Utility functions ──────────────────────────────────────────────────────

/** No-op function */
export function noop() {}

/** Always returns true */
export function alwaysTrue() {
  return true;
}

// ─── Success sentinel ───────────────────────────────────────────────────────

/** Standard success result object */
export const SUCCESS = { success: true };

// ─── Time / size constants ──────────────────────────────────────────────────

/** Milliseconds per second */
export const segmentDurationMs = 1000;

/** Seconds in one day */
export const SECONDS_PER_DAY = 86400;

/** Seconds in one week */
export const SECONDS_PER_WEEK = 604800;

/** 10,000 (used for HNS tick conversions) */
export const HNS_TICKS_10K = 10000;

/** 10,000,000 (hundred-nanosecond ticks per second) */
export const HNS_TICKS_PER_SECOND = 10000000;

/** Ratio constant 1.5 */
export const BUFFER_RATIO = 1.5;

/** 0.128 constant */
export const SMALL_BUFFER_THRESHOLD = 0.128;

/** 7.8125 constant */
export const FREQUENCY_CONSTANT = 7.8125;

/** 128 byte block size */
export const BLOCK_SIZE = 128;

/** Large time value in ms (145,152,000,000 ms ~ 4.6 years) */
export const MAX_DURATION_MS = 145152e5;

/** 100,000 constant */
export const LARGE_SEGMENT_THRESHOLD = 100000;

// ─── Player ordering ────────────────────────────────────────────────────────

/** Storage key for player instance ordering */
export const PLAYER_ORDER_KEY = '$netflix$player$order';

/** Sentinel for unset / default index */
export const UNSET_INDEX = -1;

/** Initial index value */
export const INITIAL_INDEX = 1;

// ─── Locale / encoding ──────────────────────────────────────────────────────

/** Default locale fallback */
export const DEFAULT_LOCALE = ['en-US'];

/** Bits per byte */
export const BITS_PER_BYTE = 8;

/** Max 16-bit unsigned value */
export const MAX_UINT16 = 65535;

/** 2^16 */
export const UINT16_OVERFLOW = 65536;

/** Max safe number value */
export const MAX_NUMBER = Number.MAX_VALUE;

// ─── DRM systems ────────────────────────────────────────────────────────────

/** PlayReady DRM system identifier */
export const DRM_PLAYREADY = 'playready';

/** Widevine DRM system identifier */
export const DRM_WIDEVINE = 'widevine';

/** FairPlay Streaming DRM system identifier */
export const DRM_FAIRPLAY = 'fps';

// ─── Audio codec MIME types ─────────────────────────────────────────────────

/** AAC-HE (High Efficiency) MIME type */
export const MIME_AAC_HE = 'audio/mp4; codecs="mp4a.40.5"';

/** xHE-AAC MIME type */
export const MIME_XHE_AAC = 'audio/mp4; codecs="mp4a.40.42"';

/** Dolby Digital Plus (E-AC-3) MIME type */
export const MIME_EAC3 = 'audio/mp4; codecs="ec-3"';

// ─── Video codec MIME types ─────────────────────────────────────────────────

/** H.264/AVC High profile L4.0 MIME type */
export const MIME_AVC_HIGH = 'video/mp4; codecs="avc1.640028"';

/** HEVC Main10 MIME type */
export const MIME_HEVC_MAIN10 = 'video/mp4; codecs="hev1.2.6.L153.timerHandle"';

/** Dolby Vision profile 01 MIME type */
export const MIME_DOLBY_VISION = 'video/mp4; codecs="dvhe.01000000"';

// ─── DRM system UUIDs ───────────────────────────────────────────────────────

/** PlayReady system UUID */
export const PLAYREADY_UUID = '9A04F079-9840-4286-AB92-E65BE0885F95';

/** Marlin DRM system UUID */
export const MARLIN_UUID = '29701FE4-3CC7-4A34-8C5B-AE90C7439A47';

/** Widevine system UUID */
export const WIDEVINE_UUID = 'EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED';

// ─── Netflix MP4 box UUIDs ──────────────────────────────────────────────────

/** Netflix stream identification UUIDs */
export const NETFLIX_STREAM_UUIDS = [
  '4E657466-6C69-7850-6966-665374726D21',
  '4E657466-6C69-7848-6165-6465722E7632',
];

/** Netflix auxiliary data UUID */
export const NETFLIX_AUX_UUID = 'A2394F52-5A9B-4F14-A244-6C427C648DF4';

/** Netflix frame rate UUID */
export const NETFLIX_FRAMERATE_UUID = '4E657466-6C69-7846-7261-6D6552617465';

/** Netflix encryption metadata UUID */
export const NETFLIX_ENCRYPTION_UUID = '8974DBCE-7BE7-4C51-84F9-7148F9882554';

// ─── MP4 codec four-character codes ─────────────────────────────────────────

export const FOURCC_MP4A = 'mp4a';
export const FOURCC_ENCA = 'enca';
export const FOURCC_EC3 = 'ec-3';
export const FOURCC_AVC1 = 'avc1';
export const FOURCC_ENCV = 'encv';
export const FOURCC_HVCC = 'hvcC';
export const FOURCC_HEV1 = 'hev1';
export const FOURCC_DVHE = 'dvhe';

// ─── Track numbering ────────────────────────────────────────────────────────

/** Base track index (0-based) */
export const BASE_TRACK_INDEX = 0;

/** First user track index (1-based) */
export const FIRST_TRACK_INDEX = 1;

// ─── CSS / Layout ───────────────────────────────────────────────────────────

/** Default player container CSS */
export const PLAYER_CONTAINER_CSS = 'position:relative;width:100%;height:100%;overflow:hidden';

// ─── Pre-built encrypted init segment headers (base64) ──────────────────────
// These are complete ftyp+moov MP4 init segments with PSSH boxes for
// PlayReady, Widevine and Marlin DRM systems, used to "prime" the
// SourceBuffer so that it can accept both clear and encrypted content.

/** Encrypted header for AVC (H.264) content */
export const ENCRYPTED_HEADER_AVC = 'AAAAJGZ0eXBpc282AAAAAW1jbDBpc282ZHNtc21zaXhkYXNoAAAAKWZyZWVJc29NZWRpYSBGaWxlIFByb2R1Y2VkIHdpdGggR1BBQwAAAAXwbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAABdwAAAAAAAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAzt0cmFrAAAAXHRraGQAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAYAAAADYAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAAAAAAH0gABAAAAAAKzbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAABdwAAAAABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABNZWRpYUhhbmRsZXIAAAACXm1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAh5zdGJsAAAB0nN0c2QAAAAAAAAAAgAAAQllbmN2AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAYAA2ABIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAP2F2Y0MBZAAW/+EAI2dkABasylBgd+XARAAAD6QAA6mDkgAD0JAAehKTTAHixbLAAQAFaOk7LIv9+PgAAAAAEHBhc3AAAAABAAAAAQAAAFBzaW5mAAAADGZybWFhdmMxAAAAFHNjaG0AAAAAY2VuYwABAAAAAAAoc2NoaQAAACB0ZW5jAAAAAAAAAQgAAAAABJJuTQAAAAAAAAAAAAAAFGJ0cnQAAFdDAAQxEAAA4PAAAAC5YXZjMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAGAANgASAAAAEgAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAAAD9hdmNDAWQAFv/hACNnZAAWrMpQYHflwEQAAA+kAAOpg5IAA9CQAHoSk0wB4sWywAEABWjpOyyL/fj4AAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAV0MABDEQAADg8AAAABBzdHRzAAAAAAAAAAAAAAAQc3RzYwAAAAAAAAAAAAAAFHN0c3oAAAAAAAAAAAAAAAAAAAAQc3RjbwAAAAAAAAAAAAAAOG12ZXgAAAAQbWVoZAAAAAABSRwjAAAAIHRyZXgAAAAAAAAAAQAAAAEAAAPpAAAAAAABAAAAAAGJcHNzaAAAAACaBPB5mEBChquS5lvgiF+VAAABaUoCAAAQAQCUAjwAVwBSAE0ASABFAEEARABFAFIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMgAuADAALgAwACIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiAD4ADQAKACAAIAA8AEQAQQBUAEEAPgANAAoAIAAgACAAIAA8AEQARQBDAFIAWQBQAFQATwBSAFMARQBUAFUAUAA+AE8ATgBEAEUATQBBAE4ARAA8AC8ARABFAEMAUgBZAFAAVABPAFIAUwBFAFQAVQBQAD4ADQAKACAAIAA8AC8ARABBAFQAQQA+AA0ACgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgAAAABMcHNzaAAAAAApcB/kPMdKNIxbrpDHQ5pHAAAALAAAAAQAAAAABJJuTcxdH7v6mbzxtj405AeHQcIhLEFIaAigoatAInie7Qj4AAAANHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABQIARIQAAAAAASSbk0AAAAAAAAAAA==';

/** Encrypted header for HEVC (H.265 / Main10) content */
export const ENCRYPTED_HEADER_HEVC = 'AAAAJGZ0eXBpc282AAAAAW1jbDBpc282ZHNtc21zaXhkYXNoAAAAKWZyZWVJc29NZWRpYSBGaWxlIFByb2R1Y2VkIHdpdGggR1BBQwAAAAa0bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAB1MAAAAAAAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAA/90cmFrAAAAXHRraGQAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAABQAAAALQAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAAAAAAH0gABAAAAAAN3bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAB1MAAAAABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABNZWRpYUhhbmRsZXIAAAADIm1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAuJzdGJsAAAClnN0c2QAAAAAAAAAAgAAAWtlbmN2AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABQAC0ABIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAjmh2Y0MBAiAAAACQAAAAAABd8AD9/fr6AAAPA6AAAQAYQAEMAf//AiAAAAMAkAAAAwAAAwBdkcCQoQABAEFCAQECIAAAAwCQAAADAAADAF2gAoCALRNnkeSQpEM5Kym/RhSVgLUBAQEEAAAPpAAB1MPoq978AS6AJeACXQBLwqIAAQAHRAHBcvY8kAAAABBwYXNwAAAAAQAAAAEAAAATY29scm5jbHgAAQABAAEAAAAAUHNpbmYAAAAMZnJtYWh2YzEAAAAUc2NobQAAAABjZW5jAAEAAAAAAChzY2hpAAAAIHRlbmMAAAAAAAABCAAAAAAEkm5NAAAAAAAAAAAAAAAUYnRydAAAfR0ADq1AAAfrqAAAARtodmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABQAC0ABIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAjmh2Y0MBAiAAAACQAAAAAABd8AD9/fr6AAAPA6AAAQAYQAEMAf//AiAAAAMAkAAAAwAAAwBdkcCQoQABAEFCAQECIAAAAwCQAAADAAADAF2gAoCALRNnkeSQpEM5Kym/RhSVgLUBAQEEAAAPpAAB1MPoq978AS6AJeACXQBLwqIAAQAHRAHBcvY8kAAAABBwYXNwAAAAAQAAAAEAAAATY29scm5jbHgAAQABAAEAAAAAFGJ0cnQAAH0dAA6tQAAH66gAAAAQc3R0cwAAAAAAAAAAAAAAEHN0c2MAAAAAAAAAAAAAABRzdHN6AAAAAAAAAAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAADhtdmV4AAAAEG1laGQAAAAAAAbfkgAAACB0cmV4AAAAAAAAAAEAAAABAAAD6QAAAAAAAQAAAAABiXBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAWlKAgAAEAEAlAI8AFcAUgBNAEgARQBBAEQARQBSACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADIALgAwAC4AMAAiACAAeABtAGwAbgBzAD0AIgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBtAGkAYwByAG8AcwBvAGYAdAAuAGMAbwBtAC8ARABSAE0ALwAyADAAMAA3AC8AMAAzAC8AUABsAGEAeQBSAGUAYQBkAHkASABlAGEAZABlAHIAIgA+AA0ACgAgACAAPABEAEEAVABBAD4ADQAKACAAIAAgACAAPABEAEUAQwBSAFkAUABUAE8AUgBTAEUAVABVAFAAPgBPAE4ARABFAE0AQQBOAEQAPAAvAEQARQBDAFIAWQBQAFQATwBSAFMARQBUAFUAUAA+AA0ACgAgACAAPAAvAEQAQQBUAEEAPgANAAoAPAAvAFcAUgBNAEgARQBBAEQARQBSAD4AAAAATHBzc2gAAAAAKXAf5DzHSjSMW66Qx0OaRwAAACwAAAAEAAAAAASSbk3MXR+7+pm88bY+NOQHh0HCISxBSGgIoKGrQCJ4nu0I+AAAADRwc3NoAAAAAO3vi6l51krOo8gn3NUdIe0AAAAUCAESEAAAAAAEkm5NAAAAAAAAAAA=';

/** Encrypted header for Dolby Vision (dvhe) content */
export const ENCRYPTED_HEADER_DV = 'AAAAJGZ0eXBpc282AAAAAW1jbDBpc282ZHNtc21zaXhkYXNoAAAAKWZyZWVJc29NZWRpYSBGaWxlIFByb2R1Y2VkIHdpdGggR1BBQwAAAAX3bW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAABdwAAAAAAAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAA0J0cmFrAAAAXHRraGQAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAmAAAAFWAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAAAAAAPpAABAAAAAAK6bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAABdwAAAAABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABNZWRpYUhhbmRsZXIAAAACZW1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAiVzdGJsAAAB2XN0c2QAAAAAAAAAAQAAAcllbmN2AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAmABVgBIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAwGh2Y0MBAiAAAACQAAAAAABa8AD9/fr6AAAPA6AAAQAYQAEMAf//AiAAAAMAkAAAAwAAAwBamLAkoQABAHFCAQECIAAAAwCQAAADAAADAFqgBMIBWfTZ5i5JCkQE7hCsImJ5ff6PNnL+jmUyXv6ObMv0YUITiKxJl7+jmzL9GFETmrEm/Zl+jCmnJWU36MKSsBahIgE2wgAAAwACAAADADHzze9+ALWAFrgBawAtcaIAAQAJRAHBcsKhljyQAAAAEHBhc3AAAAABAAAAAQAAABNjb2xybmNseAAJABAACQAAAAAgbWRjdjPChsQdTAu4hNA+gD0TQEICYloAAAAAMgAAAAxjbGxpJxAArwAAAFBzaW5mAAAADGZybWFodmMxAAAAFHNjaG0AAAAAY2VuYwABAAAAAAAoc2NoaQAAACB0ZW5jAAAAAAAAAQgAAAAABJJuTQAAAAAAAAAAAAAAFGJ0cnQAACRGAAVtaAABwSAAAAAQc3R0cwAAAAAAAAAAAAAAEHN0c2MAAAAAAAAAAAAAABRzdHN6AAAAAAAAAAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAADhtdmV4AAAAEG1laGQAAAAAADb8kAAAACB0cmV4AAAAAAAAAAEAAAABAAAD6QAAAAAAAQAAAAABiXBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAWlKAgAAEAEAlAI8AFcAUgBNAEgARQBBAEQARQBSACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADIALgAwAC4AMAAiACAAeABtAGwAbgBzAD0AIgBoAHQAdABwADoALwAvAHMAYwBoAGUAbQBhAHMALgBtAGkAYwByAG8AcwBvAGYAdAAuAGMAbwBtAC8ARABSAE0ALwAyADAAMAA3AC8AMAAzAC8AUABsAGEAeQBSAGUAYQBkAHkASABlAGEAZABlAHIAIgA+AA0ACgAgACAAPABEAEEAVABBAD4ADQAKACAAIAAgACAAPABEAEUAQwBSAFkAUABUAE8AUgBTAEUAVABVAFAAPgBPAE4ARABFAE0AQQBOAEQAPAAvAEQARQBDAFIAWQBQAFQATwBSAFMARQBUAFUAUAA+AA0ACgAgACAAPAAvAEQAQQBUAEEAPgANAAoAPAAvAFcAUgBNAEgARQBBAEQARQBSAD4AAAAATHBzc2gAAAAAKXAf5DzHSjSMW66Qx0OaRwAAACwAAAAEAAAAAASSbk3MXR+7+pm88bY+NOQHh0HCISxBSGgIoKGrQCJ4nu0I+AAAADRwc3NoAAAAAO3vi6l51krOo8gn3NUdIe0AAAAUCAESEAAAAAAEkm5NAAAAAAAAAAA=';

/** Encrypted header for Dolby Vision (GPAC 2.2.1 variant) content */
export const ENCRYPTED_HEADER_DV_V2 = 'AAAAJGZ0eXBpc282AAAAAW1jbDBpc282ZHNtc21zaXhkYXNoAAAAOmZyZWVJc29NZWRpYSBGaWxlIFByb2R1Y2VkIHdpdGggR1BBQyAyLjIuMS1yZXZyZWxlYXNlAAAABiBtb292AAAAbG12aGQAAAAA5NfWeuTX1noAAF3AAAAAAAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAADa3RyYWsAAABcdGtoZAAAAAHk19Zf5NfWegAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAADwAAAAhwAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAAAAAAA+kAAEAAAAAAuNtZGlhAAAAIG1kaGQAAAAA5NfWX+TX1noAAF3AAAAAAFXEAAAAAAA3aGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAD9AR1BBQzIuMi4xLXJldnJlbGVhc2UAAAAChG1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAkRzdGJsAAAB+HN0c2QAAAAAAAAAAgAAARxlbmN2AAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAA8ACHABIAAAASAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAH2h2Y0MBAiAAAACQAAAAAABa8AD9/fr6AAAPAAAAACBkdmNDAQAKDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHBhc3AAAAABAAAAAQAAABNjb2xybmNseAACAAIAAoAAAABQc2luZgAAAAxmcm1hZHZoZQAAABRzY2htAAAAAGNlbmMAAQAAAAAAKHNjaGkAAAAgdGVuYwAAAAAAAAEIAAAAAASSbk0AAAAAAAAAAAAAABRidHJ0AACamQAHyWAAAdpQAAAAzGR2aGUAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAADwAIcAEgAAABIAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAfaHZjQwECIAAAAJAAAAAAAFrwAP39+voAAA8AAAAAIGR2Y0MBAAoNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQcGFzcAAAAAEAAAABAAAAE2NvbHJuY2x4AAIAAgACgAAAABRidHJ0AACamQAHyWAAAdpQAAAAEHN0dHMAAAAAAAAAAAAAABBzdHNjAAAAAAAAAAAAAAAUc3RzegAAAAAAAAAAAAAAAAAAABBzdGNvAAAAAAAAAAAAAAA4bXZleAAAABBtZWhkAAAAAASXy9QAAAAgdHJleAAAAAAAAAABAAAAAQAAA+kAAAAAAAEAAAAAAYlwc3NoAAAAAJoE8HmYQEKGq5LmW+CIX5UAAAFpSgIAABABAJQCPABXAFIATQBIAEUAQQBEAEUAUgAgAHYAZQByAHMAaQBvAG4APQAiADQALgAyAC4AMAAuADAAIgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAPgANAAoAIAAgADwARABBAFQAQQA+AA0ACgAgACAAIAAgADwARABFAEMAUgBZAFAAVABPAFIAUwBFAFQAVQBQAD4ATwBOAEQARQBNAEEATgBEADwALwBEAEUAQwBSAFkAUABUAE8AUgBTAEUAVABVAFAAPgANAAoAIAAgADwALwBEAEEAVABBAD4ADQAKADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AAAAAExwc3NoAAAAAClwH+Q8x0o0jFuukMdDmkcAAAAsAAAABAAAAAAEkm5NzF0fu/qZvPG2PjTkB4dBwiEsQUhoCKChq0AieJ7tCPgAAAA0cHNzaAAAAADt74upedZKzqPIJ9zVHSHtAAAAFAgBEhAAAAAABJJuTQAAAAAAAAAA';

/** Encrypted header for AAC audio content */
export const ENCRYPTED_HEADER_AAC = 'AAAAIGZ0eXBpc282AAAAAWlzbzZkc21zbXNpeGRhc2gAAABJZnJlZUlzb01lZGlhIEZpbGUgUHJvZHVjZWQgd2l0aCBHUEFDIDIuMy1ERVYtcmV2NzMyNC1nYmY2MjljNjllLUhFQUQAAAACyW1vb3YAAABsbXZoZAAAAADh+ZcJ4fmXCQAAu4AAAAAAAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAIddHJhawAAAFx0a2hkAAAAB+H5lKLh+ZcJAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAJGVkdHMAAAAcZWxzdAAAAAAAAAABAAAAAAAAAAAAAQAAAAABlW1kaWEAAAAgbWRoZAAAAADh+ZSi4fmXCQAAu4AAAAAAFccAAAAAACVoZGxyAAAAAAAAAABzb3VuAAAAAAAAAAAAAAAAc291bgAAAAFIbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAEMc3RibAAAAKZzdHNkAAAAAAAAAAEAAACWbXA0YQAAAAAAAAABAAAAAAAAAAAAAgAQAAAAALuAAAAAAAByZXNkcwAAAAADZAAAAARcQBUABhoAAx/QAALzCAVN+UZDIjzA08ngIAAAEkt4gQIEBgtciAIJAggJCAAJ1AGAQIRCAAV1AGAwsAGQgAgdcgBgKHACEIAIGQAYCAAABMAK5JYATgAgAASfSwAGAQIAAAAQc3R0cwAAAAAAAAAAAAAAEHN0c2MAAAAAAAAAAAAAABRzdHN6AAAAAAAAAAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAABpzZ3BkAQAAAHByb2wAAAACAAAAAQABAAAAOG12ZXgAAAAQbWVoZAAAAAAJVBbgAAAAIHRyZXgAAAAAAAAAAQAAAAEAAAQAAAAAAAABAAA=';
