/**
 * @module DrmTestData
 * @description Static base64-encoded DRM initialization data used for capability probing.
 * Contains Widevine (PSSH), SDK key, and PlayReady test init data blobs that the
 * player uses to test EME (Encrypted Media Extensions) support without real content keys.
 *
 * @original Module_84218
 */

/**
 * Widevine PSSH (Protection System Specific Header) box for capability detection.
 * @type {string[]}
 */
export const WIDEVINE_TEST_PSSH = [
  'AAAANHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABQIARIQAAAAAAPSZ0kAAAAAAAAAAA==',
];

/**
 * Netflix SDK key test blobs for verifying key system access.
 * @type {string[]}
 */
export const SDK_KEY_TEST_DATA = [
  'c2tkOi8vbmV0ZmxpeC9BQUFBQkFBQUFBQUV3MzFBcDVKNTB0Qml4WTVMaTNYSGJFc3dKdDdybTdhdEExVWpPMkw3Q1ArckJYTT0=',
  'c2tkOi8vbmV0ZmxpeC9BQUFBQkFBQUFBQUV3MzFCczgwL0dQUmxsNXEweHl3bHhac1Nya3hjMndPRHZpWWNCMmJoWDdQOTNHQT0=',
  'c2tkOi8vbmV0ZmxpeC9BQUFBQkFBQUFBQUV3MzFDcWNFL25GeU0waXVKY1pKSi9xTkl3T0xJaGFCdnB4WEpDNGtyV2VpaGJBOD0=',
  'c2tkOi8vbmV0ZmxpeC9BQUFBQkFBQUFBQUV3MzFFamVRbC8rZTBLYWpjSEhZQkt1U0hkb21BdXhmSGlWUTNZYTFpRGJqYjF5Zz0=',
];

/**
 * PlayReady test initialization data for capability detection.
 * @type {string[]}
 */
export const PLAYREADY_TEST_INIT_DATA = [
  'AAADPHBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAxwcAwAAAQABABIDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMgAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAUwA+ADwASwBJAEQAIABBAEwARwBJAEQAPQAiAEEARQBTAEMAVABSACIAIABWAEEATABVAEUAPQAiAEEAQQBBAEEAQQBNAFkARQB4AEkARQBBAEEAQQBBAEEAQQBBAEEAQQBBAEEAPQA9ACIAPgA8AC8ASwBJAEQAPgA8AC8ASwBJAEQAUwA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBjAGEAcABwAHIAcwB2AHIAMAA2AC8AcwBpAGwAdgBlAHIAbABpAGcAaAB0ADUALwByAGkAZwBoAHQAcwBtAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AEwAVQBJAF8AVQBSAEwAPgBoAHQAdABwADoALwAvAGMAYQBwAHAAcgBzAHYAcgAwADYALwBzAGkAbAB2AGUAcgBsAGkAZwBoAHQANQAvAHIAaQBnAGgAdABzAG0AYQBuAGEAZwBlAHIALgBhAHMAbQB4ADwALwBMAFUASQBfAFUAUgBMAD4APABEAEUAQwBSAFkAUABUAE8AUgBTAEUAVABVAFAAPgBPAE4ARABFAE0AQQBOAEQAPAAvAEQARQBDAFIAWQBQAFQATwBSAFMARQBUAFUAUAA+ADwALwBEAEEAVABBAD4APAAvAFcAUgBNAEgARQBBAEQARQBSAD4A',
];
